### PR TITLE
setup spree_gateway for stripe

### LINKED ISSUE #12: stripe gateway

### PR DESCRIPTION
**Pull request by thogg4**
Close #12

### CODE REVIEW

**Comment by thogg4** [comment]
@ericsaupe can you look at this?

**Comment by ericsaupe** [comment]
@thogg4 why do they call it skrill transactions? Other than that it looks good. Simple installation of the gem. :panda_face:

**Comment by thogg4** [comment]
@ericsaupe call what skrill transactions?

**Comment by ericsaupe** [comment]
@thogg4 the table for transactions is called spree_skrill_transactions. It comes from them I was just wondering where the name comes from

**Comment by thogg4** [comment]
@ericsaupe ah i see. i believe its just for another possible gateway. this installs a lot of gateways and stripe is just one of them.

**Comment by ericsaupe** [comment]
Cool. Looks good

**Pull request merged**
